### ISSUE TITLE
Considering to use "Javascript Standard" coding style

### ISSUE THREAD

**Issue by p0o** [mymonero/mymonero-core-js#22]
It's similar to ESLint but provides easier formatting, no decision making, tooling and linter plugins for most of the editors.

We can simply just run "standard --fix" and it will format the whole codebase to a better style of coding which is more consistent with how JavaScript is written today and should be risk free.

https://github.com/standard/standard

**Comment by paulshapiro** [comment]
Hi @p0o, I've considered using this and other auto-formatters, and would be open to merging a proper implementation of standard on this repo, but I 

1. do not want it applied to the entire codebase (it doesn't justify a full review of a reformatted emscripten file); and 

2. find situations in which my formatting style works better, namely, function parameters, although that's not a limiting factor to my merging this.

I don't anticipate not having auto-formatting will become a real blocker to contributions and integrations. Let me know if that's incorrect.

**Comment by paulshapiro** [comment]
I wasn't talking about naming, parameters - formatters aren't relevant to those.. I'm referring to my carriage return and indentation of them.

I'm not hugely interested in indentation with spaces, it causes some issues, and 2space rather than 4 can be ambiguous in some scenarios.

I do agree plugins and automation can help cover bad formatting on commit but it's not a complete fix so cannot be relied on anyway.

When you find anyone who doesn't want to contribute because of the code practices then I will be very eager to confirm that and change.

**Comment by paulshapiro** [comment]
By the way, figure I should mention as you probably aren't familiar with that repo that we do use ESLint on mymonero-app-js so we already get IDE plugin help there as I do my core-js programming via that repo, but I see a good reason to add it here, now that we've got something to execute (unit tests).

**Comment by paulshapiro** [comment]
https://github.com/mymonero/mymonero-core-js/commit/35752d4d61f8a947a6e82244502d003f3f206ef1

**Comment by paulshapiro** [comment]
Going to close this unless future discussion reopens

**Comment by paulshapiro** [comment]
We (henrynguyen5 and I) have gone ahead and implemented a custom 'prettier' format, closing this out, thanks p0o

**Comment by p0o** [comment]
Great work, thank you for following up on this issue.
