### ISSUE TITLE
Module not found: Error:  Can't resolve 'electron' in mymonero-core-js/monero_utils

### ISSUE THREAD

**Issue by imerkle** [mymonero/mymonero-core-js#65]
I'm trying to use it in a browser web app not electron.

**Comment by paulshapiro** [comment]
In order to use the raw source code found in this repo, you generally want to package it up (unless you're cherry-picking which module you want to use). This project includes a script and example config file, which can be optimized for your specific needs.

As is under discussion in https://github.com/mymonero/mymonero-core-js/pull/63, it may even become a requirement that those who want to use the code in a browser compile the JS down to pre ES7 syntax. 

Ok to close this?

**Comment by paulshapiro** [comment]
Should be resolved now that we no longer reference electron in this repo
