### ISSUE TITLE
What is the minified code in cryptonote_crypto_EMSCRIPTEN.js? 

### ISSUE THREAD

**Issue by evanrolfe** [mymonero/mymonero-core-js#7]
There is some minified code in [cryptonote_crypto_EMSCRIPTEN.js](https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/cryptonote_crypto_EMSCRIPTEN.js), it looks like the code comes from a compiler? What are the origins of this code?Could you provide the original code that was compiled to javascript?

I've also raised this issue here https://github.com/moneroexamples/openmonero/issues/67 since it contains the same compiled code..

Thanks

**Comment by paulshapiro** [comment]
That was literally transpiled from the official C++ code. That's why I labeled it emscripten. Although the generation of that file was very much before my time. 
You can compare all the functions to the current Monero crypto-ops etc and see it's the same. 
If the implementations didn't match then the outputs would be wrong and it generally wouldn't be compatible with Monero. 

One thing I would like to mention is that it's relatively practically easy to hide code to exfiltrate keys in even completely unminified code. 
See https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5
However we would not be able to be solely targeted by such an attack. It would be spray and pray, basically, which means that every app which is using e.g. Electron would also be affected, which is a problem for any dependency repo (aka poisoning). For example Monero also uses deps and also distributes binaries to various repos etc. So if you want to audit the code then be sure to take all of these factors and methods into account.

**Comment by paulshapiro** [comment]
Closing this given the considerable work that has been done since then to expose compiling from scratch.
