### ISSUE TITLE
method `create_signed_transaction` has been removed?

### ISSUE THREAD

**Issue by i-xiaov** [mymonero/mymonero-core-js#89]
I don't think that `async__send_funds` is more convenient than `create_signed_transaction` for developers. Is it possible to bring it back?

**Comment by paulshapiro** [comment]
The step1, step2 methods still exist. They can be bridged again easily enough if you want by undoing the commit that removed the bridging. But it's basically a community decision as to whether they want to bloat the build with it at this point.

**Comment by paulshapiro** [comment]
By the way you'd have to implement the retry routine plus all the parsing calls plus the networking calls and callbacks yourself again. I wouldn't like to duplicate those in this codebase again as we moved them to C++ so that they can be shared by all applications which actually need them. 

I should ask: what problem makes you say it's not as convenient? the api remains basically the same for you..?

**Comment by i-xiaov** [comment]
I'm doing some offline-sign work. All UTXOs are managed by myself, so I prefer  `create_signed_transaction` which create a signed transaction directly when i passed all data it needed rather than through many callbacks.
I changed my code, it is compatible with `async__send_funds` now and it works well. So it's not a big deal.
Thanks for your reply.
